name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests-and-coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Python flake8 Lint
      uses: py-actions/flake8@v2.3.0
    - name: Run Flake8
      run: | 
        flake8
    - name: Run Pytest and Generate Coverage HTML Report
      run: |
        coverage run --source='.' -m pytest
        coverage html
        coverage report --fail-under=80
    - name: Upload Coverage HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html-report
        path: htmlcov/
