name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Run Pytest
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: htmlcov.index.html
        thresholds: '80'
        run: |
          coverage run --source='.' -m pytest
          coverage report
          coverage report html --cov="home/runner/work/Python-OC-Lettings-FR/Python-OC-Lettings-FR"
